image: atlassian/default-image:2

pipelines:
  branches:
    master:
      - step:
          name: Mirror Repository To GitHub
          script:
            - git push -f --mirror git@github.com:cosential/compass-client-js.git
      - step:
          name: Publish to NPM
          script:
            - npm install
            - npm run build
            - npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
            - npm publish