image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Publish to NPM
        script:
          - npm publish
  branches:
    master:
      - step:
          name: Mirror Repository To GitHub
          script:
            - git push -f --mirror git@github.com:cosential/compass-client-js.git
      - step:
          name: Publish to NPM
          script:
            - npm publish